import { flatCategoryOptions } from '@/features/categories/category-taxonomy';
import type { FeedCategory } from '@/features/feed/types/feed';

export const postCategoryOptions: Array<{
  groupLabel: string;
  groupValue: string;
  label: string;
  value: FeedCategory;
}> = flatCategoryOptions;

export const postCityOptions = [
  'Tbilisi',
  'Batumi',
  'Kutaisi',
  'Rustavi',
  'Zugdidi',
  'Gori',
  'Poti',
  'Kobuleti',
  'Samtredia',
  'Khashuri',
  'Senaki',
  'Zestaponi',
  'Marneuli',
  'Telavi',
  'Akhaltsikhe',
  'Ozurgeti',
  'Kaspi',
  'Chiatura',
  'Tsqaltubo',
  'Sagarejo',
  'Gardabani',
  'Borjomi',
  'Tkibuli',
  'Khoni',
  'Bolnisi',
  'Akhalkalaki',
  'Mtskheta',
  'Gurjaani',
  'Dusheti',
  'Kareli',
  'Sachkhere',
  'Dedoplistsqaro',
  'Lagodekhi',
  'Ninotsminda',
  'Abasha',
  'Tsnori',
  'Terjola',
  'Martvili',
  'Jvari',
  'Khobi',
  'Vani',
  'Baghdati',
  'Vale',
  'Tsalka',
  'Tetritsqaro',
  'Dmanisi',
  'Oni',
  'Ambrolauri',
  'Sighnaghi',
  'Tsageri',
  'Lentekhi',
  'Stepantsminda',
  'Mestia',
] as const;
